packages:
  - "packages/*"

allowBuilds:
  '@google/genai': true
  better-sqlite3: true
  electron-winstaller: true
  esbuild: true
  get-windows: true
  koffi: true
  node-pty: true
  protobufjs: true
  sharp: true
